### ISSUE TITLE
Fix non-English bible names?

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/uw-content-validation#45]
CV is Currently using GLT and GST for languages other than english.  We need to make sure that will always work going forward.

```
    const ULT = languageCode === 'en' ? 'ULT' : 'GLT';
    const UST = languageCode === 'en' ? 'UST' : 'GST';

```

**Comment by RobH123** [comment]
I'm not understanding this @PhotoNomad0. The snippet above from checkBookPackage() is correct to the best of my current understanding, although perhaps the username should also be either `unfoldingWord` or `Door43-Catalog` in order to use 'ULT' and 'UST'?

(I assume that you're aware that the `U` in 'ULT' and 'UST' specifically stands for 'unfoldingWord®' -- in times past it stood for generic 'Unlocked'. The `G` stands for generic 'Gateway Language'.)

But anyway, I'd prefer that sort of thing (i.e., all file control stuff) to be handled in the calling app.

**Comment by PhotoNomad0** [comment]
It gets a bit confusing when we have a ulb for hi.  Closing this for now.
