### ISSUE TITLE
Only one occurrence of double spaces found - should have found three

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#69]
In sytleguidist demo:
https://unfoldingword.github.io/uw-content-validation/#/Core%20Filetype%20Checking%20Functions?id=section-tn2-tsv-table-check

1. Replace contents of variable textG with this:
https://git.door43.org/cecil.new/journals/src/branch/master/koz_titus.tsv
2. Update bookID to be TIT instead of GEN

It only finds doubled spaces on first item in numbered list. But all three items have doubled spaces.

@RobH123

**Comment by RobH123** [comment]
Ummmh..that was sorta by design -- expecting that the user would search for, and fix, them all in their editor -- but probably a wrong assumption. On the other hand, seems excessive to have potentially dozens of trivial, almost-identical notices. But the suggestion has them all replaced.

Maybe a compromise is just to count the number of sets of doubled spaces and still just have one notice?
